%% Initialization script
% Loads the trajectory T in T.m generated by clicks2traj. Sets the 
% simulation time, and defines the constants which parameterize the 
% and the quad model, defined in parcontroller and parmode. This script is 
% run in the clicks2traj.m but it can also be run independently when a
% trajectory is already in T.m.

%% Load trajectory and LED-data
load('./mat/T');
load('./mat/LEDdata');

%% Simulation parameters
simTime = floor(length(T.X(1,:))/T.period);

%% Initial conditions and parameters for model
parmodel.MomInertia = diag([0.002 0.002 0.004]);                % moment of inertia [kg m^2]
parmodel.mass       = 0.5;                                      % mass [kg]
parmodel.g          = 9.81;                                     % gravity [m/s^2]
parmodel.pose0      = [T.X(1,1) T.Y(1,1) T.Z(1,1) T.PSI(1,1)];  % initial quad position and yaw
parmodel.cdrag      = 0.1;                                      % drag coefficient [-]

%% Parameters for the controller
parcontroller.k1          = 1.5; % Velocity gain high level trajectory tracking
parcontroller.k2          = 1.5; % Position D high level trajectory tracking
parcontroller.k3          = 0.6; % Position P high level trajectory tracking
parcontroller.kpsi        = 3;   % Gain for psi control low level control
parcontroller.ktauxy      = 100; % Gain for rz control low level control
parcontroller.satT        = 0.1; % Thrust saturation sat
parcontroller.feedforward = 1;   % 1 use feedforward, 0 do not

myVarList=who;

for indVar = 1:length(myVarList)
    assignin('base', myVarList{indVar}, eval(myVarList{indVar}))
end